ChangeLogTag:Thu Apr 17 16:15:24 2003  Ossama Othman  <ossama@dre.vanderbilt.edu>

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -10,7 +10,7 @@
 # 
 # -------------------------------------------------------------------------
 
-#  Copyright (C) 1999  Ossama Othman
+#  Copyright (C) 1999, 2002  Ossama Othman
 #
 #  All Rights Reserved
 #
@@ -25,44 +25,15 @@
 set -e
 
 # If paginator environment variable isn't set then use `more'.
-test -z $PAGER && PAGER=more
-
-# Flag that determines if dependency tracking should be enabled in
-# GNU Automake generated Makefile.in files.
-enable_deps=no
-
-# By default, assume that a workspace, not a release, is being bootstrapped.
-bootstrap_release=no
+PAGER=${PAGER:-more}
 
 usage()
 {
     cat <<EOF | $PAGER
-Usage: bootstrap [OPTIONS] [workspace | release]
+Usage: bootstrap [OPTIONS]
 
 Generic options:
   --help	  display this help and exit
-
-Supported options:
-  --enable-deps   enable dependency tracking for workspace    [default=no]
-
-Workspace Bootstrapping
------------------------
-    Bootstrapping a workspace causes all files necessary for
-    maintainers to build ACE or TAO to be generated.
-
-    Enabling dependency tracking via the \`--enable-deps' option causes
-    GNU Automake to generate dependency tracking rules in generated
-    Makefile.in files.  Currently those dependency tracking rules only
-    work with GNU C++, which is why dependency tracking is disabled by
-    default.
-
-Release Bootstrapping
----------------------
-    Bootstrapping a workspace for release does the same things as the
-    standard workspace bootstrapping procedure except that files that
-    are needed to build an ACE/TAO distribution are also generated
-    (e.g. man pages).  Dependency tracking is enabled by default since
-    Makefile dependencies should be included in ACE/TAO distributions.
 
 EOF
 
@@ -79,16 +50,6 @@ while test $# -gt 0; do
     --help)
 	usage 0
 	;;
-    --enable-deps)
-        enable_deps=yes
-	;;
-    workspace)
-	bootstrap_release=no
-        ;;
-    release)
-	bootstrap_release=yes
-        enable_deps=yes
-        ;;
     esac
     shift
 done
@@ -103,83 +64,76 @@ if test -d m4; then
     export PATH
   fi
 
-  # Provide some "useful" information.
-  if test $bootstrap_release = yes; then
-    echo Bootstrapping release...
-  else
-    echo Bootstrapping workspace...
-  fi
-
   # Update the NEWS file
   # For now just copy the contents of the `VERSION' file to make automake
   # happy.  Eventually, we should start putting real news in to it.
-  echo Creating a NEWS file
+  echo "Creating a NEWS file"
   cp VERSION NEWS
 
   # Generate an `aclocal.m4' file from all existing m4 macro files
   # including those in the `m4' directory.
-  echo Running aclocal
+  echo "Running aclocal"
   aclocal -I m4
 
+  # Make sure libtool support files are available.
+  echo "Running libtoolize"
+  libtoolize --automake
+
   # Generate a `config.h.in' configuration header template from `acconfig.h'.
-  echo 'Running autoheader (expect some "AC_TRY_RUN" warnings)'
-  autoheader
+  echo "Running autoheader"
+  autoheader -I m4
 
   # Generate the `configure' script from the `configure.in'.
-  echo 'Running autoconf (expect some "AC_TRY_RUN" warnings)'
+  echo "Running autoconf"
   autoconf
 
-  # Generate all `Makefile.in' templates in the directories listed in
-  # `configure.in' and add any missing files that GNU Automake needs so
-  # that the distribution and configuration processes will run properly.
-  echo Running automake
-  if test $bootstrap_release = no && test $enable_deps = no; then
-    automake --add-missing --include-deps #--verbose
-  else
-    automake --add-missing #--verbose
-  fi
+  # Invoke `automake' after `autoheader' so that all configuration
+  # headers are generate a priori.
+  echo "Running automake"
+  automake --add-missing
 
-  # Generate the man pages.
-  # Only generate man pages if bootstrapping a release.
-  if test $bootstrap_release = yes; then
-    if test -f man/man3/ACE.3; then
-      echo ACE man pages have already been generated.
-    else
-      echo 'Generating the ACE man pages (this may take several minutes)'
 
-      (ACE_ROOT=.; \
-       export ACE_ROOT; \
-       ./bin/generate_doxygen.pl -is_release -exclude_tao > /dev/null)
-    fi  # test -f man/man3/ACE.3
-  fi  # test $bootstrap_release = yes
+#   # Generate the man pages.
+#   # Only generate man pages if bootstrapping a release.
+#   if test $bootstrap_release = yes; then
+#     if test -f man/man3/ACE.3; then
+#       echo ACE man pages have already been generated.
+#     else
+#       echo 'Generating the ACE man pages (this may take several minutes)'
 
-  # Regenerate the man pages lists in the man page Makefiles.
+#       (ACE_ROOT=.; \
+#        export ACE_ROOT; \
+#        ./bin/generate_doxygen.pl -is_release -exclude_tao > /dev/null)
+#     fi  # test -f man/man3/ACE.3
+#   fi  # test $bootstrap_release = yes
 
-  if test -f man/man3/Makefile.am; then
-    # Only insert man page lists if bootstrapping a release.
-    if test $bootstrap_release = yes; then
-      echo 'Inserting ACE man page lists into appropriate Makefile.am files.'
-      ACE_MAN_PAGES=`(cd man/man3 && echo *.3)`
-    else
-      ACE_MAN_PAGES=
-    fi
+#   # Regenerate the man pages lists in the man page Makefiles.
 
-    (cd man/man3; \
-     eval "sed -e 's/^man_MANS =.*$/man_MANS = $ACE_MAN_PAGES/' \
-       Makefile.am > Makefile.am.new"; \
-     mv Makefile.am.new Makefile.am)
-    (cd man/html; \
-     eval "sed -e 's/^html_DATA =.*$/html_DATA = $ACE_HTML_MAN_PAGES/' \
-       Makefile.am > Makefile.am.new"; \
-     mv Makefile.am.new Makefile.am)
-  else
-    test -f man/man3/Makefile.am || echo 'man/man3/Makefile.am is missing!'
-    exit 1;
-  fi  # test -f man/man3/Makefile.am
+#   if test -f man/man3/Makefile.am; then
+#     # Only insert man page lists if bootstrapping a release.
+#     if test $bootstrap_release = yes; then
+#       echo 'Inserting ACE man page lists into appropriate Makefile.am files.'
+#       ACE_MAN_PAGES=`(cd man/man3 && echo *.3)`
+#     else
+#       ACE_MAN_PAGES=
+#     fi
+
+#     (cd man/man3; \
+#      eval "sed -e 's/^man_MANS =.*$/man_MANS = $ACE_MAN_PAGES/' \
+#        Makefile.am > Makefile.am.new"; \
+#      mv Makefile.am.new Makefile.am)
+#     (cd man/html; \
+#      eval "sed -e 's/^html_DATA =.*$/html_DATA = $ACE_HTML_MAN_PAGES/' \
+#        Makefile.am > Makefile.am.new"; \
+#      mv Makefile.am.new Makefile.am)
+#   else
+#     test -f man/man3/Makefile.am || echo 'man/man3/Makefile.am is missing!'
+#     exit 1;
+#   fi  # test -f man/man3/Makefile.am
 
   # Provide some more "useful" information.
-  echo Done bootstrapping.
+  echo "Done bootstrapping."
 else
-  echo ACE must be bootstrapped from the top-level ACE source directory.
+  echo "ACE must be bootstrapped from the top-level ACE source directory."
   exit 1;
 fi  # test -d m4
